/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define YYTEXT_POINTER 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_WCHAR_H 1
#define STDC_HEADERS 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define HAVE_DIRENT_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_FCNTL_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LANGINFO_H 1
#define HAVE_LIBINTL_H 1
#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_UTSNAME_H 1
#define HAVE_UNISTD_H 1
#define HAVE__BOOL 1
#define HAVE_STDBOOL_H 1
#define HAVE_FORK 1
#define HAVE_VFORK 1
#define HAVE_GETPAGESIZE 1
#define HAVE_SYMLINK 1
#define HAVE_WORKING_VFORK 1
#define HAVE_WORKING_FORK 1
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1
#define HAVE_MALLOC 1
#define HAVE_MMAP 1
#define HAVE_REALLOC 1
#define RETSIGTYPE void
#define HAVE_DUP2 1
#define HAVE_GETCWD 1
#define HAVE_GETHOSTBYNAME 1
#define HAVE_MEMSET 1
#define HAVE_MKDIR 1
#define HAVE_MUNMAP 1
#define HAVE_NL_LANGINFO 1
#define HAVE_SETLOCALE 1
#define HAVE_SOCKET 1
#define HAVE_STPCPY 1
#define HAVE_STRCASECMP 1
#define HAVE_STRCHR 1
#define HAVE_STRCSPN 1
#define HAVE_STRDUP 1
#define HAVE_STRRCHR 1
#define HAVE_STRSTR 1
#define HAVE_STRTOL 1
#define HAVE_STRTOUL 1
#define HAVE_ISASCII 1
#define HAVE_MEMMOVE 1
#define HAVE_STRNCASECMP 1
#define USE_OSX /**/
#define USE_BIFF /**/
#define USE_SOCKMSG /**/
#define USE_COMMON /**/
#define USE_GTAR /**/
#define USE_SSL /**/
#define USE_GTK3 /**/
#define HAVE_ICONV 1
#define ICONV_CONST 
#define HAVE_VISIBILITY 1
#define HAVE_STDINT_H_WITH_UINTMAX 1
#define INTDIV0_RAISES_SIGFPE 0
#define HAVE_INTTYPES_H_WITH_UINTMAX 1
#define HAVE_UNSIGNED_LONG_LONG_INT 1
#define HAVE_UINTMAX_T 1
#define HAVE_INTTYPES_H 1
#define _ALL_SOURCE 1
#define _COSMO_SOURCE 1
#define _DARWIN_C_SOURCE 1
#define _GNU_SOURCE 1
#define _HPUX_ALT_XOPEN_SOCKET_API 1
#define _NETBSD_SOURCE 1
#define _OPENBSD_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define __STDC_WANT_IEC_60559_ATTRIBS_EXT__ 1
#define __STDC_WANT_IEC_60559_BFP_EXT__ 1
#define __STDC_WANT_IEC_60559_DFP_EXT__ 1
#define __STDC_WANT_IEC_60559_EXT__ 1
#define __STDC_WANT_IEC_60559_FUNCS_EXT__ 1
#define __STDC_WANT_IEC_60559_TYPES_EXT__ 1
#define __STDC_WANT_LIB_EXT2__ 1
#define __STDC_WANT_MATH_SPEC_FUNCS__ 1
#define _TANDEM_SOURCE 1
#define __EXTENSIONS__ 1
/* end confdefs.h.  */
extern void xyzzy ();
#pragma weak xyzzy
int
main (void)
{
xyzzy();
  ;
  return 0;
}
